DaviesForumApp/Controllers/RepliesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DaviesForumApp.Data;
using DaviesForumApp.Models;
using Microsoft.PowerBI.Api.Models;

namespace DaviesForumApp.Controllers
{
    public class RepliesController : Controller
    {
        private readonly DataContext _context;

        public RepliesController(DataContext context)
        {
            _context = context;
        }
        //Search Bar
        public async Task<IActionResult> Search(string searching)
        {
            var dataContext = _context.Replies.Include(r => r.MessagePost);
            return View(dataContext.Where(x => x.Reply.StartsWith(searching) || searching == null).ToList());
        }
        // GET: Replies
        public async Task<IActionResult> Index()
        {
            var dataContext = _context.Replies.Include(r => r.MessagePost);
            return View(await dataContext.ToListAsync());
        }

        // GET: Replies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Replies == null)
            {
                return NotFound();
            }

            var replies = await _context.Replies
                .Include(r => r.MessagePost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (replies == null)
            {
                return NotFound();
            }

            return View(replies);
        }

        // GET: Replies/Create
        public IActionResult Create()
        {
            ViewData["MessagePostId"] = new SelectList(_context.Posts, "Id", "Message");
            return View();
        }

        // POST: Replies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Reply,MessagePostId")] Replies replies)
        {
            replies.Name = "Name";
            if (ModelState.IsValid)
            {
                replies.Name = HttpContext.Session.GetString("UserName");
                _context.Add(replies);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Search));
            }
            ViewData["MessagePostId"] = new SelectList(_context.Posts, "Id", "Message", replies.MessagePostId);
            return View(replies);
        }

        // GET: Replies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Replies == null)
            {
                return NotFound();
            }

            var replies = await _context.Replies.FindAsync(id);
            if (replies == null)
            {
                return NotFound();
            }
            ViewData["MessagePostId"] = new SelectList(_context.Posts, "Id", "Message", replies.MessagePostId);
            return View(replies);
        }

        // POST: Replies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Reply,Name,MessagePostId")] Replies replies)
        {
            if (id != replies.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(replies);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RepliesExists(replies.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Search));
            }
            ViewData["MessagePostId"] = new SelectList(_context.Posts, "Id", "Message", replies.MessagePostId);
            return View(replies);
        }

        // GET: Replies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Replies == null)
            {
                return NotFound();
            }

            var replies = await _context.Replies
                .Include(r => r.MessagePost)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (replies == null)
            {
                return NotFound();
            }

            return View(replies);
        }

        // POST: Replies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Replies == null)
            {
                return Problem("Entity set 'DataContext.Replies'  is null.");
            }
            var replies = await _context.Replies.FindAsync(id);
            if (replies != null)
            {
                _context.Replies.Remove(replies);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Search));
        }

        private bool RepliesExists(int id)
        {
          return (_context.Replies?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DaviesForumApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DaviesForumApp.Data;
using DaviesForumApp.Models;
using Twilio;
using Twilio.Rest.Api.V2010.Account;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Security.Cryptography;
using Scrypt;
using System.Text;

namespace DaviesForumApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly DataContext _context;

        public UsersController(DataContext context)
        {
            _context = context;
        }
        //Search Bar
        public async Task<IActionResult> Search(string searching)
        {
            
            return View(_context.Users.Where(x => x.UserName.StartsWith(searching) || searching == null).ToList());
        }
        // GET: Users
        public async Task<IActionResult> Index()
        {
              return _context.Users != null ? 
                          View(await _context.Users.ToListAsync()) :
                          Problem("Entity set 'DataContext.Users'  is null.");
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }
           
            var user = await _context.Users
                .Include(m => m.Posts)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( User user)
        {
            ScryptEncoder encoder= new ScryptEncoder();
            var registeredUser = (from c in _context.Users
                                 where c.UserName.Equals(user.UserName)
                                 select c).SingleOrDefault();
            if(registeredUser != null)
            {
                ViewBag.Error = "This username already registered.";
                return View();
            }

            
            if (ModelState.IsValid)
            {
                //Hashing Password
                Console.WriteLine(user.PassWord);
                user.PassWord = encoder.Encode(user.PassWord);
                Console.WriteLine(user.PassWord);
                user.ConfirmPassword = "";
                _context.Add(user);
                await _context.SaveChangesAsync();
                //var accountSid = "AC24d492a15cd6b997aa72021d05a0b452";
                //var authToken = "91080130215ecf62c914c218ffc0fa88";


                //TwilioClient.Init(accountSid, authToken);

                ////var mediaUrl = new[] { 
                ////    new Uri("https://upload.wikimedia.org/wikipedia/en/4/44/Fire_Emblem_Awakening_box_art.png")
                ////}.ToList();


                //var message = MessageResource.Create(
                //    body: "New user " + user.UserName + " has been created.",
                //    from: new Twilio.Types.PhoneNumber("+447700163581"),
                //    //mediaUrl: mediaUrl,
                //    to: new Twilio.Types.PhoneNumber("+447506402293")

                //);

                //Console.WriteLine(message.Sid);
                ViewBag.Error = "Registered successfully. Please login.";
                return RedirectToAction("Login", "UserLogin", new { area = "" });


            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  User user)
        {
            ScryptEncoder encoder = new ScryptEncoder();
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    user.PassWord = encoder.Encode(user.PassWord);
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Search));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'DataContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Search));
        }

        private bool UserExists(int id)
        {
          return (_context.Users?.Any(e => e.UserId == id)).GetValueOrDefault();
        }

        
    }
}

DaviesForumApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DaviesForumApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DaviesForumApp.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/777326d9ce.js" crossorigin="anonymous"></script>
</head>
<header>
    <nav class="navbar davies-colour navbar-dark navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand text-light">Davies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon icon-bar"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1 text-light">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="MessagePosts" asp-action="Search">Posts</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Replies" asp-action="Search">Replies</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Users" asp-action="Search">Users</a>
                    </li>
                </ul>
                <ul class="navbar-nav flex-right">
                    
                    <li class="nav-item p-1">
                        <a class="nav-link text-light btn-dark p-2" asp-area="" asp-controller="Home" asp-action="Index">Logout</a>
                    </li>
                    <li class="nav-item p-1">
                        <h3 style="color:white">@Context.Session.GetString("UserName") is logged in.</h3>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
</body>

<footer class="davies-colour border-top footer text-center ">
    <div class="container text-light">
        Davies &copy; 2023
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</html>

DaviesForumApp/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DaviesForumApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DaviesForumApp.styles.css" asp-append-version="true" />
</head>
<header>
    <nav class="navbar davies-colour navbar-dark navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Davies</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon icon-bar"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1 text-light">
                </ul>
                <ul class="navbar-nav flex-right">
                    <li class="nav-item p-1">
                        <a class="nav-link text-light btn-dark p-2" asp-controller="UserLogin" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item p-1">
                        <a class="nav-link text-light btn-primary p-2" asp-controller="Users" asp-action="Create">Register</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</header>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>