DaviesForumApp/Models/MessagePost.cs
using Microsoft.AspNetCore.SignalR;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DaviesForumApp.Models
{
    public class MessagePost
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Message { get; set; }
        [Required]
        public string Title { get; set; }


        [DisplayName("UserId")]
        public int UserId { get; set; }
        //User Relations
        public User? User { get; set; }
       
        
        //Replies Relations
        public List<Replies>? Replies { get; set; }
    }
}

DaviesForumApp/Controllers/MessagePostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DaviesForumApp.Data;
using DaviesForumApp.Models;
using Microsoft.PowerBI.Api.Models;
using Microsoft.PowerBI.Api;

namespace DaviesForumApp.Controllers
{
   
    public class MessagePostsController : Controller
    {
        private readonly DataContext _context;



        public MessagePostsController(DataContext context)
        {
            _context = context;
        }
        //Search Bar
        public async Task<IActionResult> Search(string searching)
        {
            var dataContext = _context.Posts.Include(m => m.User);
            return View(dataContext.Where(x => x.Title.StartsWith(searching) || searching == null).ToList());
        }
        
        public async Task<IActionResult> Searcher(string searching)
        {
            return View(_context.Posts.Where(x => x.Title.StartsWith(searching) || searching == null).ToList());
        }
        // GET: MessagePosts
        public async Task<IActionResult> Index()
        {
            var dataContext = _context.Posts.Include(m => m.User);
            return View(await dataContext.ToListAsync());
        }

        // GET: MessagePosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var messagePost = await _context.Posts
                .Include(m => m.User)
                .Include(k => k.Replies)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (messagePost == null)
            {
                return NotFound();
            }

            return View(messagePost);
        }

        // GET: MessagePosts/Create
        public IActionResult Create()
            
        {
            //string check = HttpContext.Session.GetString("UserName");
            //var sessionUser = (from c in _context.Users
            //                      where c.UserName.Equals(check)
            //                      select c).SingleOrDefault();

            //ViewBag.UserId = sessionUser.UserId;
            //var sessionUser = (from c in _context.Users where c.UserName.Equals(HttpContext.Session.GetString("UserName")) select c).SingleOrDefault();
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserName");
            return View();
        }

        // POST: MessagePosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( MessagePost messagePost)
        {
           
            
            if (ModelState.IsValid)
            {
                //messagePost.UserId = (int)HttpContext.Session.GetInt32("UserId");
                _context.Add(messagePost);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Search));
            }
         
            return View(messagePost);
        }

        // GET: MessagePosts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var messagePost = await _context.Posts.FindAsync(id);
            if (messagePost == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserName", messagePost.UserId);
            return View(messagePost);
        }

        // POST: MessagePosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MessagePost messagePost)
        {
            if (id != messagePost.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(messagePost);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessagePostExists(messagePost.Id))
                    {
                        System.Console.WriteLine("Error");
                        return NotFound();
                        
                    }
                    else
                    {
                        System.Console.WriteLine("Error");
                        throw;
                    }
                }
                return RedirectToAction(nameof(Search));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "UserId", "UserName", messagePost.UserId);
            return View(messagePost);
        }

        // GET: MessagePosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var messagePost = await _context.Posts
                .Include(m => m.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (messagePost == null)
            {
                return NotFound();
            }

            return View(messagePost);
        }

        // POST: MessagePosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set 'DataContext.Posts'  is null.");
            }
            var messagePost = await _context.Posts.FindAsync(id);
            if (messagePost != null)
            {
                _context.Posts.Remove(messagePost);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Search));
        }

        private bool MessagePostExists(int id)
        {
          return (_context.Posts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

DaviesForumApp/Views/MessagePosts/Create.cshtml
@using Microsoft.AspNetCore.Http;
@model MessagePost

@{

}

<h1>Write a new Post</h1>


<hr />
<!-- <div class="row">
<div class="col-md-4">
<form asp-action="Create">
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<div class="form-group">
<label>User:</label>
<select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
</div>
<div class="form-group">
<label asp-for="Title" class="control-label"></label>
<input asp-for="Title" class="form-control" />
<span asp-validation-for="Title" class="text-danger"></span>
</div>
<div class="form-group">
<label asp-for="Message" class="control-label"></label>
<input asp-for="Message" class="form-control" />
<span asp-validation-for="Message" class="text-danger"></span>
</div>
<div class="form-group">
<input type="submit" value="Create" class="btn btn-primary" />
</div>
</form>
</div>
</div>

<div>
<a asp-action="Search">Back to List</a>
</div> -->

<div class="text-center">
    <section class="vh-50 gradient-custom">
        <div class="container py-1 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-8 col-xl-5">
                    <div style="border-radius: 5px;">
                        <div class="card-body p-5 speech-bubble-2 text-light text-center">
                            <div class="mb-md-1 mt-md-1 pb-2">
                                <form asp-action="Create" class="col-12 text-center">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group p-2">
                                        <label>User</label>
                                       @* <input asp-for="UserId" class="form-control" value="@Context.Session.GetInt32("UserID")">  @Context.Session.GetString("UserName") </input>*@
                                      @* <input type="text" asp-for="UserId" class="form-control" value="@Context.Session.GetInt32("UserID")" placeholder="@Context.Session.GetString("UserName")"/>*@
                                        <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                                    </div>
                                    <div class="form-group p-2">
                                        <label asp-for="Title" class="control-label"></label>
                                        <input asp-for="Title" class="form-control" />
                                        <span asp-validation-for="Title" class="text-danger"></span>
                                    </div>
                                    <div class="form-group p-2">
                                        <label asp-for="Message" class="control-label"></label>
                                        <textarea asp-for="Message" class="form-control"></textarea>
                                        <span asp-validation-for="Message" class="text-danger"></span>
                                    </div>
                                    <br />
                                    <button type="submit" class="btn btn-success p-2 pt-2 pb-2" value="Create">Create</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<div>
    <a asp-action="Search" class="btn btn-dark p-2">Back</a>
</div>

DaviesForumApp/Views/MessagePosts/Delete.cshtml
@model DaviesForumApp.Models.MessagePost

@{
    ViewData["Title"] = "Delete";
}

@{
    
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div id="darkM">
    <h4>MessagePost</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <button type="button" id="delete-item-btn" onClick="deleteCheck()" class="btn btn-danger" data-toggle="modal" data-target="delete-modal">Delete</button>
        <a asp-action="Search" class="btn btn-dark p-2">Back</a>
    </form>
</div>

<!-- Modal -->

<div id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="delete-modal">
    <div class="modal-dialog modal-confirm">
        <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title text-dark">Delete Confirmation</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
            <p class="text-dark">Are you sure you want to delete @Model.Message? This cannot be undone.</p>
            </div>
            <div class="modal-footer">
            <form asp-action="Delete">
                <button type="submit" asp-action="Delete" value="Delete" class="btn btn-danger">Delete</button>
            </form>
            </div>
        </div>   
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script type="text/javascript" language="JavaScript">
            function deleteCheck() {
                const modal = document.getElementById("delete-modal");

                const btn = document.getElementById("delete-item-btn");

                const button = document.getElementsByClassName("close")[0];

                btn.onclick = function () {
                    modal.style.display = "block"
                }

                button.onclick = function () {
                    modal.style.display = "none"
                }

                window.onclick = function (event) {
                    if (event.target == modal) {
                        modal.style.display = "none";
                    }
                };
            }
        </script>
    }
    
}

DaviesForumApp/Views/MessagePosts/Details.cshtml
@model DaviesForumApp.Models.MessagePost

@{
    ViewData["Title"] = "Details";
   
}



<h1>Further Information</h1>
<br/>
<div class="container">
<div class="row">
<div class="col">
    <div class="card">
        <div class="card-header d-flex justify-content-between p-3">
            <p class="fw-bold mb-0">@Html.DisplayNameFor(model => model.Title)</p>
        </div>
        <div class="card-body">
            <p class="mb-0">
            <p>@Html.DisplayFor(model => model.Title)</p>
            </p>
        </div>
    </div>
    <div class="card">
        <div class="card-header d-flex justify-content-between p-3">
            <p class="fw-bold mb-0">@Html.DisplayNameFor(model => model.Message)</p>
            </div>
            <div class="card-body">
            <p class="mb-0">
            <p>@Html.DisplayFor(model => model.Message)</p>
            </p>
        </div>
    </div>
    <div class="card">
        <div class="card-header d-flex justify-content-between p-3">
            <p class="fw-bold mb-0">@Html.DisplayNameFor(model => model.User)</p>
        </div>
        <div class="card-body">
            <p class="mb-0">
            <p>@Html.DisplayFor(model => model.User.UserName)</p>
            </p>
        </div>
    </div>
    <div class="card">
        <div class="card-header d-flex justify-content-between p-3">
            <p class="fw-bold mb-0">@Html.DisplayNameFor(model => model.User.UserEmail)</p>
        </div>
        <div class="card-body">
            <p class="mb-0">
            <p>@Html.DisplayFor(model => model.User.UserEmail)</p>
            </p>
        </div>
    </div>
</div>

    <!-- <hr />
    <div class="row d-flex m-2">
        <div class="col-md-8 col-lg-6">
            <div class="card shadow-0 border">
            <div class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.Message)</strong>
            </div>
            <div class="col-sm-10">
                <p>@Html.DisplayFor(model => model.Message)</p>
            </div>
            <div class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.Title)</strong>
            </div>
            <div class="col-sm-10">
                <p>@Html.DisplayFor(model => model.Title)</p>
            </div>
            <div class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.User)</strong>
            </div>
            <div class="col-sm-10">
                <p>@Html.DisplayFor(model => model.User.UserName)</p>
            </div>
            <div class="col-sm-2">
                <strong>@Html.DisplayNameFor(model => model.User.UserEmail)</strong>
            </div>
            <div class="col-sm-10">
                <p>@Html.DisplayFor(model => model.User.UserEmail)</p>
            </div>
            </div>
        </div>
    </div>
    
    <dl class="row d-flex justify-content-center">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.UserName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.User.UserEmail)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.User.UserEmail)
        </dd> -->
        <br />
        <br />
    <div class="col">
        <dt class="col-12 text-center">
            <h3>Replies:</h3>
        </dt>
        <br />
        <br />
        @{
        var altRow = true;
        foreach (var item in Model.Replies)
        
        {
            if (altRow == true)
            {<div class="row d-flex justify-content-center m-2">
                <div class="col-md-8 col-lg-6">
                    <div class="card shadow-0 border">
                    <div class="card-body speech-bubble p-4">
                        <div class="card mb-4">
                        <div class="card-body">
                            <p class="fw-bold mb-0">@item.Reply</p>
                            
                            <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <strong><p class="small mb-0 ms-2">- @item.Name</p></strong>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
                    altRow = false;
                } else if (altRow == false) 
            {
            <div class="row d-flex justify-content-center m-2">
                <div class="col-md-8 col-lg-6">
                    <div class="card shadow-0 border">
                    <div class="card-body speech-bubble-2 p-4">
                        <div class="card mb-4">
                        <div class="card-body">
                            <p class="fw-bold mb-0">@item.Reply</p>

                            <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <strong><p class="small mb-0 ms-2">@item.Name</p></strong>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                    </div>
                    altRow = true;
                };
                
        }
        
        }
</div>
</div>
</div>
<br/>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-success"><i class="fa-solid fa-pen-to-square"></i> Edit</a> |
    <a asp-action="Search" class="btn btn-dark">Back to List</a>
</div>

DaviesForumApp/Views/MessagePosts/Edit.cshtml
@model DaviesForumApp.Models.MessagePost

@{
    ViewData["Title"] = "Edit";
    
}


<h1 class="p-2">Edit This Post</h1>
<hr />

<br />

<!-- <div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Message" class="control-label"></label>
                <input asp-for="Message" class="form-control" />
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Search">Back</a>
</div> -->

<div class="text-center"> 
    <section class="vh-50 gradient-custom">
        <div class="container py-1 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-8 col-xl-5">
                    <div style="border-radius: 5px;">
                        <div class="card-body p-5 form-style text-dark text-center">
                            <div class="mb-md-1 mt-md-1 pb-2">
                                <form asp-action="Edit" class="col-12 text-center">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <input type="hidden" asp-for="Id" />
                                    <div class="form-group p-2">
                                        <label asp-for="UserId" class="control-label"></label>
                                        <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                                        <span asp-validation-for="UserId" class="text-danger"></span>
                                    </div>
                                    <div class="form-group p-2">
                                        <label asp-for="Title" class="control-label"></label>
                                        <input asp-for="Title" class="form-control" />
                                        <span asp-validation-for="Title" class="text-danger"></span>
                                    </div>
                                    <div class="form-group p-2">
                                        <label asp-for="Message" class="control-label"></label>
                                        <textarea asp-for="Message" class="form-control"></textarea>
                                        <span asp-validation-for="Message" class="text-danger"></span>
                                    </div>
                                    <br />
                                    <button type="submit" class="btn btn-success p-2 pt-2 pb-2" value="Save">Update</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<div>
    <a asp-action="Search" class="btn btn-dark p-2">Back</a>
</div>

DaviesForumApp/Views/MessagePosts/Index.cshtml
@model IEnumerable<DaviesForumApp.Models.MessagePost>

@{
    ViewData["Title"] = "Index";
   
}

<h1>List of Messages</h1>
<p>
    <a asp-controller="MessagePosts" asp-action="Search">Search</a>
</p>
<p>
    <a asp-action="Create">Create New Message</a>
</p>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.Id)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Title)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Message)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.User.UserName)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.User.UserId)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.User.Department)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.User.UserEmail)</th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Id)</td>
            <td>@Html.DisplayFor(modelItem => item.Title)</td>
            <td>@Html.DisplayFor(modelItem => item.Message)</td>
            <td>@Html.DisplayFor(modelItem => item.User.UserName)</td>
            <td>@Html.DisplayFor(modelItem => item.User.UserId)</td>
            <td>@Html.DisplayFor(modelItem => item.User.Department)</td>
            <td>@Html.DisplayFor(modelItem => item.User.UserEmail)</td>
            
             <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
        </tr>
        }
    </tbody>
</table>

DaviesForumApp/Views/MessagePosts/Search.cshtml
@model IEnumerable<DaviesForumApp.Models.MessagePost>
<body style="background-color: black; color: white">
<br/>
<h1>Message Board</h1>
<br/>
<div style="text-align: center; justify-content: center">
@using (Html.BeginForm("Search", "MessagePosts", FormMethod.Get)){
    
    @Html.TextBox("searching")<input type="submit" value="Search Bar" asp-action="Search" asp-controller="MessagePosts"/>
}
<br />
<p>
    <a asp-action="Create" class="btn btn-warning"><i class="fa-solid fa-pen"></i>  Create New Message</a>
</p>
</div>
<br/>

@*<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">@Html.DisplayNameFor(model => model.Id)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Title)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.Message)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.User.UserName)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.User.UserId)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.User.Department)</th>
            <th scope="col">@Html.DisplayNameFor(model => model.User.UserEmail)</th>

            <th>Functionality</th>
        </tr>
    </thead>
    <tbody>*@
@if (Model.Count() == 0)
{
    <td colspan="8" style="color:red">
        No Matches Available
    </td>
}
else if(Model.Count() != 0)
{
   @* @foreach (var item in Model)
    {
    <tr>
                <td>@Html.DisplayFor(modelItem => item.Id)</td>
                <td>@Html.DisplayFor(modelItem => item.Title)</td>
                <td>@Html.DisplayFor(modelItem => item.Message)</td>
                <td>@Html.DisplayFor(modelItem => item.User.UserName)</td>
                <td>@Html.DisplayFor(modelItem => item.User.UserId)</td>
                <td>@Html.DisplayFor(modelItem => item.User.Department)</td>
                <td>@Html.DisplayFor(modelItem => item.User.UserEmail)</td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success btn-sm mr-2"><i class="fa-solid fa-pen-to-square"></i></a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm mr-2"><i class="fa-solid fa-circle-info"></i></a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm mr-2"><i class="fa-solid fa-trash"></i></a>
                </td>
    </tr>
    }*@
}

        
   @* </tbody>
</table>*@

<br />


    @foreach (var item in Model)
    {
            <div class="card" style="background-color: #10444C; color: white">
          <div class="card-header">
            Title: @Html.DisplayFor(modelItem => item.Title)
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
                  <p>Message: @Html.DisplayFor(modelItem => item.Message)</p>
                      <footer class="blockquote-footer" style="color: white">@Html.DisplayFor(modelItem => item.User.UserName) from @Html.DisplayFor(modelItem => item.User.Department)</footer>
            </blockquote>
          </div>
              
              <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success btn-sm mr-2"><i class="fa-solid fa-pen-to-square"></i></a>
              <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning btn-sm mr-2"><i class="fa-solid fa-circle-info"></i></a>
              <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm mr-2"><i class="fa-solid fa-trash"></i></a>
        </div>
       
        <br />
    }

</body>